import random

import pygame
SCREEN_WIDTH=1280
SCREEN_HEIGHT=640
BACKGROUND_COLOR = (0, 128, 0)
SOLDIER_WIDTH=80
SOLDIER_HEIGHT=90
SOLDIER_IMG = pygame.image.load('soldier.png')
GRASS_IMG = pygame.image.load('grass.png')
GRASS_HEIGHT=100
GRASS_WIDTH=100
SOLDIER_X = 0
SOLDIER_Y = 0
SOLDIER_MIDBOTTOM_X = 30
SOLDIER_MIDBOTTOM_Y = 90
